
# https://graphite.com/guides/github-actions-on-pull-requests
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'lib-sounds/**'

defaults:
  run:
    shell: bash
    working-directory: ./lib-sounds

# https://github.com/libsdl-org/SDL/issues/10947
jobs:
# https://github.com/docker/build-push-action
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          # tags: user/app:latest

  uv:
    env:
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk" # Or "dummy" if no audio output is needed at all
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # - name: Install ALSA utilities
      #   # run: sudo apt-get update && sudo apt-get install -y alsa-utils
      #   run: sudo apt-get install -y alsa-utils

      # - name: Verify ALSA setup
      #   run: aplay -L # Should list the dummy device

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
      # no  --locked on lib package
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -s