name:  pygame-display-with-sound


# https://graphite.com/guides/github-actions-on-pull-requests
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'pygame/display-with-sound/**'

defaults:
  run:
    shell: bash
    working-directory: ./pygame/display-with-sound

# https://github.com/libsdl-org/SDL/issues/10947
jobs:
  uv-example:
    env:
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk" # Or "dummy" if no audio output is needed at all
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install ALSA utilities
        # run: sudo apt-get update && sudo apt-get install -y alsa-utils
        run: sudo apt-get install -y alsa-utils

      # - name: Load snd-dummy module
      #   run: |
      #     sudo modprobe snd-dummy
      #     echo "alias char-major-116 snd" | sudo tee /etc/modprobe.d/myalias.conf
      #     echo "alias snd-card-0 snd-dummy" | sudo tee -a /etc/modprobe.d/myalias.conf
      #     sudo modprobe snd-dummy # Load again after alias if needed

      # - name: Configure ALSA for dummy device
      #   run: |
      #     echo "pcm.!default { type hw card 0 }" | sudo tee /etc/asound.conf
      #     echo "ctl.!default { type hw card 0 }" | sudo tee -a /etc/asound.conf

      - name: Verify ALSA setup
        run: aplay -L # Should list the dummy device

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests