# name:  pygame-sprite


# https://graphite.com/guides/github-actions-on-pull-requests
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'pygame/keyboard_input/**'

defaults:
  run:
    shell: bash
    working-directory: ./pygame/keyboard_input

# https://github.com/libsdl-org/SDL/issues/10947
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install ALSA utilities
        # run: sudo apt-get update && sudo apt-get install -y alsa-utils
        run: sudo apt-get install -y alsa-utils

      - name: Verify ALSA setup
        run: aplay -L # Should list the dummy device

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests -s